type Mutation {
    createNewUser(user: CreateUserInput): CreateNewUserResult

    createNewDiscount(input: CreateNewDiscountInput): CreateNewDiscountResult

    createManyDiscounts(input: CreateManyDiscountsInput): CreateManyDiscountsResult

    createManyChecks(input: CreateManyChecksInput): CreateManyChecksResult

    createAdmin(user: CreateAdimInput): CreateAdminResult

    createReport(input: CreateReportInput): CreateReportResult
}

union CreateNewUserResult =  CreateNewUserSuccess | InternalError | InvalidInputError
union CreateNewDiscountResult =  CreateNewDiscountSuccess | InternalError | InvalidInputError
union CreateManyDiscountsResult =  CreateManyDiscountsSuccess | InternalError | InvalidInputError
union CreateManyChecksResult =  CreateManyChecksSuccess | InternalError | InvalidInputError
union CreateAdminResult =  CreateAdminSuccess | InternalError | InvalidInputError
union CreateReportResult =  CreateReportSuccess | InternalError | InvalidInputError

input CreateUserInput{
    name:String!
}

input CreateAdimInput{
    name:String!
    email:String
    password:String
}

input CreateManyDiscountsInput{
    discounts: [CreateNewDiscountInput]
}

input CreateNewDiscountInput{
    user: ID
    description: String!
    amount: Int!
}

input CreateReportInput{
    amountPerHour: Int
    usersPay: [UsersPayInput]
}

input Checksinput{
    check: ID
}

input UsersPayInput{
    user:ID
    total: Int
    discounts: [CreateNewDiscountInput]
    checks: [Checksinput]
}

input CreateManyChecksInput{
    user: ID
    checks:[ChecksInput]
}

input ChecksInput{
    startTime: Date
    endTime: Date
}

type CreateNewUserSuccess{
    user: User
}

type CreateNewDiscountSuccess{
    discount: Discount
}

type CreateManyDiscountsSuccess{
    discounts: [Discount]
}

type CreateManyChecksSuccess{
    checks: [Check]
}

type CreateAdminSuccess{
    user: User
}

type CreateReportSuccess{
    report: Report
}
