type Mutation {
    createNewUser(user: CreateUserInput): CreateNewUserResult

    createNewDiscount(input: CreateNewDiscountInput): CreateNewDiscountResult

    createManyDiscounts(input: CreateManyDiscountsInput): CreateManyDiscountsResult

    createManyChecks(input: CreateManyChecksInput): CreateManyChecksResult
}

union CreateNewUserResult =  CreateNewUserSuccess | InternalError | InvalidInputError
union CreateNewDiscountResult =  CreateNewDiscountSuccess | InternalError | InvalidInputError
union CreateManyDiscountsResult =  CreateManyDiscountsSuccess | InternalError | InvalidInputError
union CreateManyChecksResult =  CreateManyChecksSuccess | InternalError | InvalidInputError

input CreateUserInput{
    name:String!
}

input CreateManyDiscountsInput{
    discounts: [CreateNewDiscountInput]
}

input CreateNewDiscountInput{
    user: ID
    description: String!
    amount: Int!
}

input CreateManyChecksInput{
    user: ID
    checks:[ChecksInput]
}

input ChecksInput{
    startTime: Date
    endTime: Date
}

type CreateNewUserSuccess{
    user: User
}

type CreateNewDiscountSuccess{
    discount: Discount
}

type CreateManyDiscountsSuccess{
    discounts: [Discount]
}

type CreateManyChecksSuccess{
    checks: [Check]
}
