type Query {
    showUsers(filter: FilterUsers, filterUser: FilterShowUser): ShowUsersResult
}


union ShowUsersResult = ShowUsersSuccess | InvalidInputError | InternalError

type ShowUsersSuccess {
    showUsersConnection: ShowUsersConnection
}

input FilterShowUser{
    role: [Role]
}

input FilterUsers{
    pagination: FilterPagination
}