scalar Date

enum Role{
    USER
    ADMIN
    SUPER_USER
}

type User{
    _id: ID
    name: String
    role: [Role]
}

type Discount{
    _id: ID
    description: String
    amount: Int
    user: User
    email: String
}

type Check{
    _id: ID
    user: User
    startTime: Date
    endTime: Date
    isActive: Boolean
}

type Report{
    _id: ID
    owner: User
    amountPerHour: Int
    dateCreated: Date
    usersPay: [UsersPayInformation]
}

type UsersPayInformation{
    user: User
    totalPay: Int
    hoursWorked: Int
    discounts: [Discount]
    checks: [Check]
}

type ShowUsersConnection{
    pageInfo: Pagination
    total: Int
    edges: [User]
}

type ShowChecksConnection{
    pageInfo: Pagination
    total: Int
    edges: [Check]
}