enum Role{
    USER
    ADMIN
    SUPER_USER
}

type User{
    _id: ID
    name: String
    role: [Role]
}

type Discount{
    _id: ID
    description: String
    amount: Int
    user: User
}

type ShowUsersConnection{
    pageInfo: Pagination
    total: Int
    edges: [User]
}