
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: connectPoint
    env_file:
      - .env.local
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 9091:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb

  api: 
    build: .
    container_name: Backend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env.local
    depends_on:
      - mongodb
  

volumes:
  mongodb_data_container: